#ifndef CONFIG_BUILD_CONFIG_H
#define CONFIG_BUILD_CONFIG_H

#define FW_VERSION_MAJOR    1
#define FW_VERSION_MINOR    0
#define FW_VERSION_PATCH    0

#define HW_VERSION_MAJOR    1
#define HW_VERSION_MINOR    0

#define DEFAULT_MODBUS_ADDRESS  247
#define MODBUS_BAUDRATE         19200

#endif // CONFIG_BUILD_CONFIG_H
